using UnityEngine;
using UnityEngine.SceneManagement;

/*
 * This controls volume sync across the game runtime. The audio source reads the settings file generated by this script.
 * On wake, it locates the audio source in scene and passes the master vol param stored in AudioData.
 * The GameObject persists across Load_Save, Menu, and Options only — it destroys itself
 * if any other scene is loaded.
 * Exposes a static Instance so other scripts (e.g. VolumeSlider) can reach the
 * surviving AudioSource without needing an Inspector reference.
 *
 * Made by: Yoko Parks
 * Last Modified: 04/13/26
 */
public class AudioSync : MonoBehaviour
{
    public static AudioSync Instance { get; private set; } // Accessible by other scripts

    [SerializeField] private AudioData audioData; // AudioData passed in the sys
    public AudioSource Source { get; private set; } // Active audio src in memory

    // Scenes this object is allowed to persist across
    private readonly string[] allowedScenes = { "Load_Save", "menu", "Options" };



    void Awake() // Executed on pgrm wake
    {
        Source = GetComponent<AudioSource>(); // Find audio src in alloc mem

        // Only check for a duplicate if an instance was already carried over from
        // another scene — skip this check on the very first load in menu
        if (Instance != null && Instance != this)
        {
            // A carried-over instance already exists — destroy this fresh duplicate
            Destroy(gameObject);
            return;
        }

        // First load — claim the instance and persist
        Instance = this;
        DontDestroyOnLoad(gameObject); // Carry this object across scene loads

        // Listen for scene changes so we can self-destruct if leaving allowed scenes
        SceneManager.sceneLoaded += OnSceneLoaded;
    }



    void Start() // After wake this executes
    {
        // Only run Start logic on the surviving instance
        if (Instance != this) return;

        if (audioData != null && Source != null)
        {
            Source.volume = audioData.masterVolume; // Audio Vol overwrite
        }

        if (Source != null && !Source.isPlaying)
        {
            Source.Play(); // Begin playback if not already playing
        }
    }



    private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        // Check if the newly loaded scene is in the allowed list
        foreach (string allowed in allowedScenes)
        {
            if (scene.name == allowed) return; // allowed — do nothing
        }

        // Scene is not in the allowed list — clean up and destroy
        SceneManager.sceneLoaded -= OnSceneLoaded;
        Instance = null;
        Destroy(gameObject);
    }
}