using UnityEngine;

/*
 * This controls volume sync across the game runtime. The audio source reads the settings file generated by this script.
 * On wake, it locates the audio source in scene and passes the master vol param stored in AudioData
 *
 * Made by: Yoko Parks
 * Last Modified: 04/13/26 
 */
public class AudioSync : MonoBehaviour
{
    [SerializeField] private AudioData audioData; //AudioData passed in the sys
    private AudioSource source; //Active audio src in memory



    void Awake() //Executed on pgrm wake
    {
        source = GetComponent<AudioSource>(); //Find audio src in alloc mem
    }



    void Start() //After wake this executes
    {
        if (audioData != null && source != null)
        {
            source.volume = audioData.masterVolume; //Audio Vol overwrite
        }
    }
}